### PR TITLE
MBP - Add gamepad support

### PR DESCRIPTION
**Pull request by thearst3rd**
This adds support for playing MBHaxe with a gamepad. I tested it with an XInput controller, but according to the docs it should support dualshock as well (and maybe others through SDL).

While in game, it handles pretty well. Navigating the menus on the other hand is pretty awful, you're still gonna need to use a mouse and keyboard to do most things. But a few button mappings were added to the menu at least.

Tested in both hashlink and js. For some reason, in js, the start button stops working in my configuration. Gonna look into it

### CODE REVIEW

**Comment by thearst3rd** [comment]
Hmm, encountering an issue with mobile touch controls combined with a gamepad loaded. Don't merge this yet

**Comment by thearst3rd** [comment]
Things should be fixed now. Mobile still has issues getting the correct mapping, but the mappings were the same as opening https://gamepadviewer.com/ on mobile so I don't think it's an issue with MBHaxe. At least it doesn't crash like it used to. I also got the start button working as intended on js.

**Comment by RandomityGuy** [comment]
Are you going to update it for MBG as well?

**Comment by thearst3rd** [comment]
Yes I was planning on backporting to the MBG branch as well :+1:

**Pull request merged**
